version: "3.8"
services:
  api:
    build:
      context: ../api/
      dockerfile: dockerfile
    ports:
      - "5000:3002"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ../api/:/app
      - /app/node_modules
    command: npm run dev
  www:
    build:
      context: ../app/
      dockerfile: dockerfile
    volumes:
      - '../app/:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true